name: Appointments Microservice CI/CD

on:
  pull_request:
    paths:
      - 'appointments/**'
  push:
    branches:
      - main

jobs:
  build-and-push-docker-appointments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image for Appointments microservice
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        DOCKER_TAG=$(echo $GITHUB_SHA | head -c 7)
        docker buildx create --use
        docker buildx build -t fatima4321/appointments-service:$DOCKER_TAG -f ./appointments/Dockerfile .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fatima4321/appointments-service:$DOCKER_TAG

  update-docker-compose:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Docker Compose file
      run: |
        sed -i 's/appointments:.*/appointments:'"$DOCKER_TAG"'/' docker-compose.yml
