apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsUser: 1000  # Run the container as a non-root user
      initContainers:
      - name: init-container
        image: ubuntu:latest
        command: ['sh', '-c', 'echo "Your Name: Fatima Aamir" && sleep 5']
      containers:
      - name: frontend
        image: fatima4321/frontend-service:latest
        env:
        - name: DOCTORS_SERVICE_URL
          value: "http://doctors-service:9090"
        - name: APPOINTMENTS_SERVICE_URL
          value: "http://appointments-service:7070"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /hello
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /hello
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
