apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      securityContext:
        runAsUser: 1000  # Run the container as a non-root user
      initContainers:
      - name: init-container
        image: ubuntu:latest
        command: ['sh', '-c', 'echo "Your Name: Ali Kahoot" && sleep 5']
      containers:
      - name: doctors
        image: fatima4321/doctors-service:latest
        volumeMounts:
        - name: details-volume
          mountPath: /user/details.txt
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /hello
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /hello
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 5
      volumes:
      - name: details-volume
        configMap:
          name: doctors-configmap
          items:
          - key: details.txt
            path: details.txt
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
