apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors
        image: docker.io/library/doctors:latest
        resources:
          limits:
            cpu: "0.5"  
            memory: "512Mi"  
          requests:
            cpu: "0.1"  
            memory: "256Mi"  # adjust as per your requirements
        livenessProbe:
          httpGet:
            path: /hello
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /hello
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
