name: CI/CD Pipeline

on:
  pull_request:
    paths:
      - 'appointments/**'
      - 'doctors/**'
      - 'frontend/**'
  push:
    branches:
      - main

jobs:
  build-and-push-docker-appointments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image for Appointments microservice
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        DOCKER_TAG=$(echo $GITHUB_SHA | head -c 7)
        docker build -t fatima4321/appointments-service:$DOCKER_TAG -f ./appointments/Dockerfile .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fatima4321/appointments-service:$DOCKER_TAG

  build-and-push-docker-doctors:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image for Doctors microservice
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        DOCKER_TAG=$(echo $GITHUB_SHA | head -c 7)
        docker build -t fatima4321/doctors-service:$DOCKER_TAG -f ./doctors/Dockerfile .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fatima4321/doctors-service:$DOCKER_TAG

  build-and-push-docker-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image for Frontend microservice
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        DOCKER_TAG=$(echo $GITHUB_SHA | head -c 7)
        docker build -t fatima4321/frontend-service:$DOCKER_TAG -f ./frontend/Dockerfile .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fatima4321/frontend-service:$DOCKER_TAG

  update-docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Docker Compose file
      run: |
        sed -i 's/appointments:.*/appointments:latest/' docker-compose.yml
        sed -i 's/doctors:.*/doctors:latest/' docker-compose.yml
        sed -i 's/frontend:.*/frontend:latest/' docker-compose.yml

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Docker Compose
      run: docker-compose up -d
